### ISSUE TITLE
Example of shortcode which is not a Gutenberg block and adding npm third party libraries

### ISSUE THREAD

**Issue by stcalica** [youknowriad/wp-js-plugin-starter#11]
I'm going to try this out and try to submit a pull request. 
But is there fallbacks or hurdles to trying to do this? 
How do you handle using a library from `npm` and including the dependency with wordpress' react abstraction?

**Comment by youknowriad** [comment]
Hi There! this repository is not about proviging examples of Gutenberg blocks, it's about a boilerplate starter with docs to build any JavaScript based WordPress plugins. Not necessarily blocks. 

Thanks for your understanding.
