### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by paulmiller3000** [youknowriad/wp-js-plugin-starter#12]
Right out of the gate in step 1, I received a database error after opening http://localhost:8888/. The standard "Error establishing a database connection".

I verified Docker Desktop is up-to-date and my docker-compose.yml matches the example. Docker has permission to my drives. What am I missing?

**Comment by youknowriad** [comment]
I guess your mysql docker instance was not ready yet, try restarting multiple times.
Otherwise, you can try to remove the docker instances and restart

```
docker-compose stop && docker-compose rm
docker-compose up -d
```

**Comment by paulmiller3000** [comment]
Will do! And, in retrospect, I should not have opened this as an issue, since it's a Docker thing. Everything else worked perfectly. Thanks!
